global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'marketplace'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8083']
